tlsnotary/tlsn

mpc-aio/examples/ot_ws.rs
mpc-aio/src/ot/extension/receiver.rs
mpc-core/Cargo.toml
mpc-core/benches/ot.rs
mpc-core/examples/ot.rs
mpc-core/examples/ote.rs
mpc-core/examples/ote_random.rs
mpc-core/proto/ot.proto
mpc-core/src/ot/base/errors.rs
mpc-core/src/ot/base/mod.rs
mpc-core/src/ot/base/receiver.rs
mpc-core/src/ot/base/sender.rs
mpc-core/src/ot/extension/errors.rs
mpc-core/src/ot/extension/mod.rs
mpc-core/src/ot/extension/receiver.rs
mpc-core/src/ot/extension/sender.rs
mpc-core/src/ot/mod.rs
mpc-core/src/proto/core/ot.rs

I've implemented a supertrait over top of ExtSendCore and ExtReceiveCore to allow for Beaver Derandomization

beaver derandomization for OT extension

---

mpc-core/src/ot/extension/kos15/mod.rs
mpc-core/src/ot/extension/kos15/receiver/error.rs
mpc-core/src/ot/extension/kos15/receiver/mod.rs
mpc-core/src/ot/extension/kos15/receiver/state.rs
mpc-core/src/ot/extension/kos15/sender/mod.rs
mpc-core/src/ot/extension/kos15/sender/state.rs

This PR implements OT splitting

Readded OT splitting after KOS refactor

---

tls-2pc-core/src/ghash/utils.rs

Repairs overflow in test in some cases.

Repair test_masked_xtable

---

mpc-aio/src/protocol/ot/kos/sender.rs
mpc-aio/src/protocol/ot/mod.rs
mpc-core/src/ot/extension/kos15/matrix.rs
mpc-core/src/ot/extension/kos15/receiver/mod.rs
mpc-core/src/ot/extension/kos15/sender/mod.rs
mpc-core/src/ot/extension/kos15/sender/state.rs

misc comments

---

tlsn/tlsn-core/Cargo.toml
tlsn/tlsn-core/src/merkle.rs

Updated rs_merkle to 1.4.1

---

CHANGELOG.md
CONTRIBUTING.md
README.md

Added contributor guidelines

---

point-addition/Cargo.toml
point-addition/src/conversion.rs
point-addition/src/lib.rs
point-addition/src/mock.rs
tls/tls-mpc/src/setup.rs

- Improve manifest
- Check for panics/unwraps
- Add tracing
- Improve doc

Release preparation for crate `point-addition`

---

aead/Cargo.toml
aead/src/aes_gcm/mod.rs
aead/src/aes_gcm/tag.rs
aead/src/lib.rs

- Improve manifest
- Adapt/add doc
- Add tracing
- Check for panics/unwraps

Release preparation for crate `aead`

---

.github/workflows/rust.yml

Use toolchain from dtolnay instead of outdated actions-rs

---

uid-mux/Cargo.toml
uid-mux/src/lib.rs

- Tidy up manifest
- Improve comments
- Add stricter linting rules
- Add tracing

Release preparation for crate `uid-mux`

---

.github/workflows/rust.yml

+ explicitly set workspace in rust-cache action
#277
#278

Updated rust-cache in GitHub action

---

components/integration-tests/Cargo.toml
components/key-exchange/Cargo.toml
components/key-exchange/src/config.rs
components/key-exchange/src/exchange.rs
components/point-addition/Cargo.toml
components/point-addition/src/lib.rs
components/tls/tls-mpc/Cargo.toml
components/tls/tls-mpc/src/follower.rs
components/tls/tls-mpc/src/leader.rs

- Tidy up manifest
- Improve comments
- Add tracing

Release preparation for crate `key-exchange`

---

components/prf/Cargo.toml
components/prf/hmac-sha256-circuits/Cargo.toml
components/prf/hmac-sha256-circuits/src/hmac_sha256.rs
components/prf/hmac-sha256-circuits/src/lib.rs
components/prf/hmac-sha256-circuits/src/prf.rs
components/prf/hmac-sha256-circuits/src/session_keys.rs
components/prf/hmac-sha256-circuits/src/verify_data.rs
components/prf/hmac-sha256/Cargo.toml
components/prf/hmac-sha256/src/prf.rs

- Tidy up manifests
- Improve doc
- Check for panics
- Add tracing

Release preparation for workspace `prf`

---

components/cipher/Cargo.toml
components/cipher/block-cipher/Cargo.toml
components/cipher/block-cipher/src/cipher.rs
components/cipher/block-cipher/src/circuit.rs
components/cipher/stream-cipher/Cargo.toml
components/cipher/stream-cipher/src/cipher.rs
components/cipher/stream-cipher/src/config.rs
components/cipher/stream-cipher/src/lib.rs
components/cipher/stream-cipher/src/stream_cipher.rs

- add tracing
- tidy up manifests

Release preparation for workspace `cipher`

---

components/actors/actor-ot/Cargo.toml
components/actors/actor-ot/src/receiver.rs
components/actors/actor-ot/src/sender.rs
components/aead/Cargo.toml
components/cipher/Cargo.toml
components/integration-tests/Cargo.toml
components/key-exchange/Cargo.toml
components/point-addition/Cargo.toml
components/prf/Cargo.toml
components/prf/hmac-sha256/Cargo.toml
components/prf/hmac-sha256/src/prf.rs
components/tls/tls-mpc/Cargo.toml
components/universal-hash/Cargo.toml
components/universal-hash/src/ghash/ghash_inner/mod.rs
tlsn/Cargo.toml
tlsn/tlsn-core/src/substrings/proof.rs

This PR bumps the mpz dependency to the new commit which removes the tokio dependency.

Bump mpz dependency to 86f1687

---

components/tls/Cargo.toml
components/tls/tls-backend/Cargo.toml
components/tls/tls-backend/src/lib.rs
components/tls/tls-client-async/Cargo.toml
components/tls/tls-client-async/src/lib.rs
components/tls/tls-client/Cargo.toml
components/tls/tls-client/src/backend/standard.rs
components/tls/tls-core/Cargo.toml
components/tls/tls-mpc/Cargo.toml
components/tls/tls-mpc/src/config.rs
components/tls/tls-mpc/src/error.rs
components/tls/tls-mpc/src/follower.rs
components/tls/tls-mpc/src/leader.rs
components/tls/tls-mpc/src/lib.rs
components/tls/tls-mpc/src/msg.rs
components/tls/tls-mpc/src/setup.rs
components/tls/tls-server-fixture/Cargo.toml
components/tls/tls-server-fixture/src/lib.rs

- Tidy up manifest
- Improve doc
- Add tracing

Release preparation for workspace `tls`

---

components/tls/tls-mpc/src/follower.rs
components/tls/tls-mpc/src/lib.rs
tlsn/tlsn-prover/src/lib.rs
tlsn/tlsn-prover/src/state.rs

misc comments from reviewing https://github.com/tlsnotary/tlsn/pull/325

Pr325 comments

---

README.md

Show badges on top of README page on GitHub

---

.github/workflows/rust.yml

Check that benches compile in GitHub workflow

---

.github/workflows/ci.yml
components/tls/tls-client/examples/internal/bench.rs
tlsn/examples/twitter/twitter_dm.rs

Enable clippy for examples in ci build

---

components/tls/tls-client/src/conn.rs
notary-server/README.md
notary-server/build.rs
notary-server/notary-server.Dockerfile
notary-server/notary-server.Dockerfile.dockerignore
notary-server/openapi.yaml
notary-server/src/domain.rs
notary-server/src/server.rs

Add git commit hash and timestamp to info endpoint to provide more version info to client

Add git commit hash and timestamp to info endpoint

---

.github/workflows/ci.yml
.github/workflows/rustdoc.yml

Optimise test to use release profile to speed up notary server integration test as it was taking close to 2 mins

Optimise test to use release profile to speed up notary server integration test

---

components/prf/hmac-sha256-circuits/Cargo.toml
components/prf/hmac-sha256-circuits/src/prf.rs

Use ring 0.17 in prf tests too

---

components/tls/tls-client/src/backend/standard.rs
components/tls/tls-client/tests/api.rs
notary-server/config/config.yaml
notary-server/openapi.yaml
tlsn/examples/Cargo.toml
tlsn/examples/discord/discord_dm.rs
tlsn/examples/interactive/README.md
tlsn/examples/interactive/interactive.rs
tlsn/examples/src/lib.rs
tlsn/examples/twitter/twitter_dm.rs

Example for the interactive verifier.
To the reviewers: please check the code, structure and comments. I expect people to copy this code and use it as a template for getting started.

interactive verifier example

---

tlsn/tests-integration/tests/verify.rs
tlsn/tlsn-core/src/proof/session.rs
tlsn/tlsn-prover/src/http/mod.rs
tlsn/tlsn-prover/src/tls/mod.rs
tlsn/tlsn-prover/src/tls/notarize.rs
tlsn/tlsn-prover/src/tls/prove.rs
tlsn/tlsn-prover/src/tls/state.rs

This PR fixes some typos and comments for clarity and correctnes.

docs: misc fixups

---

tlsn/tlsn-prover/src/http/mod.rs
tlsn/tlsn-prover/src/lib.rs
tlsn/tlsn-prover/src/tls/mod.rs
tlsn/tlsn-prover/src/tls/notarize.rs
tlsn/tlsn-verifier/src/tls/config.rs
tlsn/tlsn-verifier/src/tls/mod.rs
tlsn/tlsn-verifier/src/tls/notarize.rs
tlsn/tlsn-verifier/src/tls/verify.rs

This PR fixes style in tlsn-prover/verifier crates.

docs: fix style

---

components/tls/Cargo.toml
components/tls/tls-client-async/Cargo.toml
components/tls/tls-client-async/tests/test.rs
components/tls/tls-server-fixture/Cargo.toml
components/tls/tls-server-fixture/src/lib.rs
notary-server/Cargo.toml
notary-server/src/error.rs
notary-server/src/server.rs
notary-server/src/service/axum_websocket.rs
notary-server/src/service/tcp.rs
notary-server/tests/integration_test.rs
tlsn/Cargo.toml
tlsn/examples/interactive/interactive.rs
tlsn/tests-integration/Cargo.toml
tlsn/tests-integration/tests/defer_decryption.rs
tlsn/tests-integration/tests/notarize.rs
tlsn/tests-integration/tests/verify.rs
tlsn/tlsn-server-fixture/Cargo.toml
tlsn/tlsn-server-fixture/src/lib.rs

Addresses https://github.com/tlsnotary/tlsn/issues/445
This PR updates all hyper dependencies in this repo to 1.1, as well as updating axum and a few other dependant crates

Update hyper dependencies for notary-server and all server fixtures

---

.github/scripts/build-server.sh
cd-scripts/appspec-scripts/after_install.sh
cd-scripts/appspec-scripts/start_app.sh
cd-scripts/appspec-scripts/stop_app.sh

Fix failed deployment: https://github.com/tlsnotary/tlsn/actions/runs/9655529116, where the `target/release/` folder is not in `notary/server` but `notary`

Fix cd script.

---

crates/examples/Cargo.toml
crates/examples/interactive/README.md
crates/examples/interactive/interactive.rs

docs: fix and improve interactive example

---

.github/workflows/ci.yml
crates/components/aead/Cargo.toml
crates/components/aead/src/aes_gcm/error.rs
crates/components/aead/src/aes_gcm/mod.rs

This PR fixes the deadlock in our aead unit tests and adds the tests back. More info here #548.

Fix aead deadlock in unit tests

---

crates/core/src/merkle.rs

fix(core): remove serde flatten

---

crates/wasm-test-runner/run.sh
pre-commit-check.sh

This script can be used to run checks before pushing changes to the repository.
It is a good approximation of what CI will do.

Add convenience script to run most ci checks locally

---

crates/data-fixtures/Cargo.toml
crates/examples/Cargo.toml
crates/notary/tests-integration/Cargo.toml
crates/tests-integration/Cargo.toml
crates/tls/mpc/Cargo.toml
crates/tls/server-fixture/Cargo.toml
crates/wasm-test-runner/Cargo.toml

Version bump correction

---

crates/core/src/attestation.rs
crates/core/src/attestation/proof.rs
crates/core/src/hash.rs
crates/core/src/index.rs
crates/core/src/merkle.rs
crates/core/src/request.rs
crates/core/src/signing.rs
crates/core/src/transcript/encoding.rs
crates/core/src/transcript/encoding/proof.rs
crates/core/src/transcript/encoding/tree.rs
crates/notary/server/src/signing.rs
crates/prover/src/notarize.rs
crates/prover/src/prove.rs
crates/tls/mpc/src/follower.rs
crates/verifier/src/lib.rs
crates/verifier/src/notarize.rs
crates/verifier/src/verify.rs

This PR fixes some grammar and wording.

style: fix grammar and wording

---

crates/components/deap/src/lib.rs

This PR improves DEAP tests to show that different deltas are used in each execution. Also fixes grammar.

test: improve test, fix grammar

---

crates/core/src/transcript/encoding/encoder.rs

This PR simplifies the encoding logic.

perf(core): simplify encoding logic

---

crates/common/src/encoding.rs
crates/core/src/transcript.rs
crates/core/src/transcript/encoding/encoder.rs
crates/notary/server/src/server.rs
crates/prover/src/lib.rs
crates/prover/src/notarize.rs
crates/verifier/src/lib.rs
crates/verifier/src/notarize.rs
crates/verifier/src/verify.rs

This PR makes no functional changes, just improves naming and comments and addresses @th4s 's comments raised in https://github.com/tlsnotary/tlsn/pull/696

chore: improve naming and comments

---

crates/examples/attestation/present.rs
crates/examples/attestation/prove.rs
crates/examples/attestation/verify.rs
crates/examples/interactive/interactive.rs
crates/examples/src/lib.rs

This PR fixes formatting in the examples crate.

chore(examples): fix formatting

---

crates/wasm/src/prover/config.rs
crates/wasm/src/verifier/config.rs

This PR exposes the max_records  config to wasm prover and verifier.

feat(wasm): allow max records config

---

Cargo.lock
crates/examples/attestation/README.md
crates/examples/interactive/README.md
crates/server-fixture/server/Cargo.toml
crates/server-fixture/server/README.md
crates/server-fixture/server/src/lib.rs
crates/server-fixture/server/src/main.rs

feat: add logging to server fixture (#901)

---

.github/workflows/ci.yml
.gitignore
CONTRIBUTING.md
Cargo.lock
crates/benches/binary/README.md
crates/benches/binary/benches.Dockerfile
crates/notary/server/notary-server.Dockerfile

https://github.com/tlsnotary/tlsn/issues/884

build: Lock + document Cargo.lock

---

crates/mpc-tls/src/config.rs
crates/prover/src/config.rs
crates/verifier/src/config.rs

This PR adapts the configuration logic to the new default for `NetworkSetting`.

fix(prf): adapt logic to new default setting

---

crates/wasm/src/prover/config.rs

This PR exposes the recently added client authentication feature to `tlsn-js`.
A PR for changes in `tlsn-js` will follow soon.

chore(wasm): expose client auth config to js
