tlsnotary/tlsn

.github/workflows/rust.yml

If we decide to turn off github workflows for draft PRs, this should do the trick.

Disable workflow for draft PRS

---

mpc-core/src/ot/extension/kos15/receiver.rs
mpc-core/src/ot/extension/kos15/sender.rs

- Remove `self.padding` of KOS15Receiver
- Remove the entire padding after transposition for both sender and
receiver

Improvements for padding in KOS15

---

tls-2pc-core/build.rs
tls-2pc-core/src/lib.rs
tls-2pc-core/src/prf/follower.rs
tls-2pc-core/src/prf/leader.rs
tls-2pc-core/src/prf/mod.rs
tls-2pc-core/src/prf/utils.rs

This PR fixes all clippy lints in the `tls-2pc-core` subcrate **except** those in the `ghash` module, because this will be replaced by #111 soon.

Fix clippy lints for tls-2pc-core

---

gf2-128/tests/ot_integration.rs
mpc-aio/src/protocol/ot/kos/mod.rs
mpc-aio/src/protocol/ot/kos/receiver.rs
mpc-aio/src/protocol/ot/kos/sender.rs
mpc-core/benches/ot.rs
mpc-core/examples/ote.rs
mpc-core/examples/ote_random.rs
mpc-core/src/msgs/ot.rs
mpc-core/src/ot/extension/kos15/mod.rs
mpc-core/src/ot/extension/kos15/receiver/mod.rs
mpc-core/src/ot/extension/kos15/sender/error.rs
mpc-core/src/ot/extension/kos15/sender/mod.rs

This PR adds the feature that for KOS OT, the sender now needs to input the number of OTs, he wants to generate. If this does not meet the receiver's value in the setup message, an error is returned.

OT: Add sender input for the number of OTs to generate

---

mpc/mpc-core/src/ot/extension/kos15/mod.rs
mpc/mpc-core/src/ot/extension/kos15/receiver/error.rs
mpc/mpc-core/src/ot/extension/kos15/receiver/mod.rs
mpc/mpc-core/src/ot/extension/kos15/receiver/state.rs

This PR:
- makes it an error if the count of OT Sender's ciphertexts doesn't match the count of derandomized choice bits
- consistently names receiver's choice bits as `choices` and the random bits from Random OT setup as `rand_choices`

Ot wrong ciphertext count

---

mpc/share-conversion-core/src/a2m.rs

This PR simplifies a2m
It is easier to reason about the protocol if we break it down in 2 steps: (sender's additive share is x, receiver's is y)
1. the sender sends to peer `y * random`
2. the sender mixes in `x * random` into the last OT.

simplified a2m

---

mpc/garble/mpc-garble/src/protocol/deap/error.rs
mpc/garble/mpc-garble/src/protocol/deap/mod.rs
mpc/garble/mpc-garble/src/protocol/deap/vm.rs

This PR
adds a PeerEncodings trait to DEAP VM to enable to extract peer's encodings. These encodings can be used by the Prover to create commitments.

PeerEncodings trait

---

components/actors/actor-ot/Cargo.toml
components/aead/Cargo.toml
components/cipher/Cargo.toml
components/integration-tests/Cargo.toml
components/key-exchange/Cargo.toml
components/point-addition/Cargo.toml
components/prf/Cargo.toml
components/tls/tls-mpc/Cargo.toml
components/universal-hash/Cargo.toml
tlsn/Cargo.toml

This PR adapts all dependencies on the mpz repository in the **old** location `https://github.com/tlsnotary/mpz` to the **new** location `https://github.com/privacy-scaling-explorations/mpz`.

Adapt dependency of mpz to new repo location

---

components/tls/Cargo.toml
components/tls/tls-client-async/Cargo.toml
components/tls/tls-client-async/src/lib.rs
components/tls/tls-client-async/tests/test.rs
components/tls/tls-client/src/backend/standard.rs
components/tls/tls-client/src/conn.rs
components/tls/tls-server-fixture/Cargo.toml
components/tls/tls-server-fixture/src/lib.rs
tlsn/tests-integration/tests/test.rs

This PR:
- introduces fixes in tls-client-async and tests.
- adds a new tls server fixture (with the existing hyper-based one it was not possible to test certain server behaviour).
-  does not treat absence of close_notify as an error.

Async tls client fix. New server fixture and tests. Don't rely on close_notify.

---

components/aead/Cargo.toml
components/key-exchange/Cargo.toml
components/prf/hmac-sha256/Cargo.toml
components/tls/tls-mpc/Cargo.toml
tlsn/tlsn-notary/Cargo.toml
tlsn/tlsn-prover/Cargo.toml

This PR recursively enables tracing, i.e. if someone enables tracing in e.g. the `tlsn-prover` library, this also enables tracing for all other tlsn dependencies on which `tlsn-prover` depends. This PR closes #259.

Recursively enable tracing

---

tlsn/tlsn-prover/src/lib.rs

This PR removes the expectation for a TLS server to send close_notify. Most of the servers don't send it anyway (tested with https://github.com/themighty1/rustls/blob/1ffbf848789bd233c4f36a7b3f04fc31912c4371/examples/src/bin/simpleclient.rs#L57)
Additionally, we will be changing our protocol (the exact approach is tbd) so there will be no need to reveal the MAC key to the Notary.

fix: remove close_notify guard

---

.github/workflows/rustdoc.yml
tlsn/examples/Cargo.toml

This PR builds `rustdoc` for the `dev` branch and publishes the result to the `gh-pages` branch.
Preview at <https://tlsnotary.github.io/tlsn/>

Publish rustdoc to docs folder

---

notary-server/README.md
tlsn/examples/discord/discord_dm.rs
tlsn/examples/twitter/twitter_dm.rs

Make it generic to parse notary url in the prover example — so that we can just easily use ip address or domain name as the notary host

Modify notary url parsing to make it generic for both ip and domain

---

notary-server/README.md

This PR adapts the README with the correct link to pull the docker image for the notary server. Closes #381

Adapted readme for docker image

---

notary-server/Cargo.toml
notary-server/src/server.rs

Disable CORS as the notary server is meant to be consumed by all origins.
cc @yuroitaki  @0xtsukino

Make CORS permissive

---

CONTRIBUTING.md

This PR adds a minimal style guide.

docs: add style guide

---

components/universal-hash/src/ghash/ghash_inner/mod.rs

This PR adjusts the number of OLEs that need to be allocated for GHASH to account for free squaring.

Adapt GHASH preprocessing to free squaring.

---

crates/components/stream-cipher/src/config.rs

This PR adds the missing description to the execution modes. First discussed in https://github.com/tlsnotary/tlsn/pull/455#discussion_r1531848868

docs: describe execution modes

---

crates/wasm/Cargo.toml

This PR fixes our currently failing wasm build and closes #564. The fix is to set a specific wasm-bindgen version.

Fix wasm build failure

---

crates/benches/bin/prover.rs
crates/common/src/config.rs
crates/examples/discord/discord_dm.rs
crates/examples/interactive/interactive.rs
crates/examples/src/lib.rs
crates/examples/twitter/twitter_dm.rs
crates/notary/client/src/client.rs
crates/notary/tests-integration/tests/notary.rs
crates/prover/src/tls/config.rs
crates/tests-integration/Cargo.toml
crates/tests-integration/tests/defer_decryption.rs
crates/tests-integration/tests/notarize.rs
crates/tests-integration/tests/verify.rs
crates/tls/mpc/src/config.rs
crates/tls/mpc/src/follower.rs
crates/tls/mpc/src/leader.rs
crates/tls/mpc/tests/test.rs
crates/verifier/src/tls/config.rs
crates/wasm-test-runner/src/tlsn_fixture.rs
crates/wasm/src/prover/config.rs
crates/wasm/src/prover/mod.rs
crates/wasm/src/tests.rs
crates/wasm/src/verifier/config.rs

This PR makes defer-decryption default and introduces the necessary config changes.

Make defer-decryption default

---

Cargo.toml
crates/benches/browser/native/Cargo.toml
crates/wasm-test-runner/Cargo.toml

this PR bumps tlsn-utils (reason: websocket-relay was merged into dev)

use the latest rev of tlsn-utils

---

crates/benches/browser/wasm/Cargo.toml
crates/wasm/Cargo.toml

Reverts tlsnotary/tlsn#662
This PR has a problem: `workerHelpers.worker.js` is no longer generated. Reverting this change for now.

Revert "build: Update wasm-bindgen and wasm-bindgen-rayon dependency"

---

crates/notary/server/Cargo.toml
crates/notary/server/config/config.yaml
crates/notary/server/tee/config/config.yaml

this pr modifies the info and health endpoints to use relative paths which are compatible with the standalone notary-server and hosted versions behind reverse proxies

notary-server: fix paths

---

crates/mpc-tls/src/config.rs
crates/mpc-tls/tests/test.rs
crates/prover/src/config.rs
crates/verifier/src/config.rs

This PR partially addresses #738 
Right now the count is derived from `max_recv_online`, which is incorrect. We have to preprocess J0s for `max_recv`.

fix: compute recv record count from max_recv

---

.github/codecov.yml

Disable coverage annotations and comments in GitHub with a `codecov.yml` file

Codecov yaml

---

.github/workflows/rustdoc.yml
crates/wasm/build-docs.sh

This PR adds `tlsn-wasm` to the API documentation.
tlsn-wasm needs to be build with the wasm32-target. The doc build is now more complicated than before, so I moved it to a separate script.

Add `tlsn-wasm` to API docs

---

crates/notary/client/src/client.rs
crates/notary/server/src/server.rs

This PR improves the error message in cases when the client or notary unexpectedly get a connection without TLS enabled.

misc(notary): improve error msg when tls is expected

---

crates/core/src/connection.rs
crates/tls/client/src/verifybench.rs

This PR fixes failed tested caused by `webpki-roots` upgrade from 0.26.9 -> 0.26.10 in which some of the root certs were invalidated.
Closes https://github.com/tlsnotary/tlsn/issues/822

test: webpki roots fixes

---

crates/benches/binary/README.md
crates/benches/binary/bench.toml
crates/benches/binary/benches.Dockerfile
crates/benches/browser/native/src/lib.rs
crates/benches/browser/wasm/.cargo/config.toml
crates/benches/browser/wasm/Cargo.toml
crates/benches/browser/wasm/pkg/index.js
crates/benches/browser/wasm/pkg/worker.js
crates/benches/browser/wasm/rust-toolchain.toml
crates/benches/browser/wasm/src/lib.rs

This PR adds changes to the browser bench crate to make it run again.
The benches were run successfully in gh actions multiple times https://github.com/tlsnotary/tlsn/actions/workflows/bench.yml

browser bench fixes

---

crates/benches/library/src/lib.rs
crates/common/src/config.rs
crates/prover/src/config.rs
crates/tests-integration/tests/notarize.rs
crates/tests-integration/tests/verify.rs
crates/wasm/src/prover/config.rs

This PR moves the config option `defer_decryption_from_start` from the `ProverConfig` into the `ProtocolConfig`.

Move `defer_decryption_from_start` into `ProtocolConfig`

---

Cargo.lock
Cargo.toml
crates/components/hmac-sha256/src/hmac.rs

This PR bumps mpz dependency to the latest version and uses the new `update` method from `mpz-hash`

chore:  bump mpz and adapt `update` method call in `hmac-sha256`

---

crates/common/src/config.rs
crates/components/hmac-sha256/benches/prf.rs
crates/components/hmac-sha256/src/config.rs
crates/mpc-tls/src/config.rs
crates/prover/src/config.rs
crates/verifier/src/config.rs

This PR fixes a bug in the default logic and sets the reduced PRF variant as default. If `NetworkSetting::HighBandwidth` is selected the normal PRF is selected.

fix(prf): set correct default logic

---

crates/common/src/config.rs

This PR reverts the default back to using the full MPC PRF implementation. Benchmarking shows that the reduced variant currently is too latency sensitive and would cause performance regression at >100Mbps bandwidth levels.

refactor(mpc-tls): default to full-mpc PRF

---

crates/wasm/src/prover/mod.rs
crates/wasm/src/tests.rs
crates/wasm/src/types.rs

Needed for interactive prover-verifier flow on wasm side e.g. https://github.com/tlsnotary/tlsn-js/blob/main/demo/interactive-demo/prover-ts/src/app.tsx#L98, where one can do
```ts
const reveal: Reveal = {
server_identity: true,
sent: subtractRanges(
...
```

fix(wasm): expose reveal server identity.

---

crates/harness/docker.md

The user may locally have old version of `rust` and `debian` images. They may have incompatible glibc version. Pulling the latest images will prevent incompatibility.

fix(harness): pull latest docker images

---

crates/harness/build.wasm.sh

When checking out the repo for the first time and trying to build a harness, the user will get an error without a custom wasm-pack

fix(harness): add custom wasm-pack to build script

---

crates/harness/core/src/lib.rs
crates/harness/executor/src/provider.rs
crates/harness/runner/src/executor.rs
crates/harness/runner/src/lib.rs

This PR improves harness stability esp. for wasm:
- increase timeout for long running benches
- dont log a non-critical chrome debug protocol error 
- make sure the server executor has enough time to become ready (I ran a few times into errors when the client executor tried to connect when the server wasn't yet ready)
Supersedes https://github.com/tlsnotary/tlsn/pull/946

fix(harness): improve harness stability

---

Cargo.lock
Cargo.toml
crates/tlsn/src/prover.rs
crates/tlsn/src/verifier.rs

This PR bumps mpz and updates to use a newly added zk config

chore: use zk config; bump mpz

---

Cargo.toml
crates/harness/executor/Cargo.toml
crates/wasm/Cargo.toml

This PR reduces the generated Wasm size by ~9% (from 9,266,036 to 8,444,117 bytes) by adjusting the wasm profile settings.
Notes
* Benchmarks have not been run, but I expect no negative performance impact
* Setting `lto = "fat"` was tested: it increases build time but does not produce a meaningful size improvement compared to lto = true.

Reduce WASM size with wasm profile settings
